workspace(name = "com_github_dhalperi_rules_jvm")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "org_pubref_rules_maven",
    commit = "3a63c612b9192db72685751d82e0a2be432a7497",
    remote = "https://github.com/dhalperi/rules_maven",
    shallow_since = "1554829738 -0700",
)

load("@org_pubref_rules_maven//maven:rules.bzl", "maven_repositories", "maven_repository")

maven_repositories()

maven_repository(
    name = "guava",
    transitive_deps = [
        "25ea2e8b0c338a877313bd4672d3fe056ea78f0d:com.google.code.findbugs:jsr305:3.0.2",
        "39b109f2cd352b2d71b52a3b5a1a9850e1dc304b:com.google.errorprone:error_prone_annotations:2.1.3",
        "6a806eff209f36f635f943e16d97491f00f6bfab:com.google.guava:guava:26.0-jre",
        "ed28ded51a8b1c6b112568def5f4b455e6809019:com.google.j2objc:j2objc-annotations:1.1",
        "cea74543d5904a30861a61b4643a5f2bb372efc4:org.checkerframework:checker-qual:2.5.2",
        "775b7e22fb10026eed3f86e8dc556dfafe35f2d5:org.codehaus.mojo:animal-sniffer-annotations:1.14",
    ],
    deps = [
        "com.google.guava:guava:26.0-jre",
    ],
)

load("@guava//:rules.bzl", "guava_compile")

guava_compile()
